#!/bin/bash

# Instagram API with Instagram Login Setup Script
# This script helps you set up Instagram Login (simpler than Facebook Login)

echo "🚀 Instagram API with Instagram Login Setup"
echo "==========================================="
echo ""

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file from template..."
    cp env.template .env
    echo "✅ .env file created"
else
    echo "📝 .env file already exists"
fi

echo ""
echo "🔧 Next Steps:"
echo "=============="
echo ""
echo "1. 🌐 Go to Instagram Developers Console:"
echo "   https://developers.facebook.com/"
echo ""
echo "2. 📱 Create a new Instagram Business App:"
echo "   - Click 'My Apps' → 'Create App'"
echo "   - Select 'Business' (not Consumer)"
echo "   - App Name: 'PixelForge AI'"
echo ""
echo "3. 🔗 Add Instagram Graph API:"
echo "   - In your app dashboard, click 'Add Product'"
echo "   - Find 'Instagram Graph API' and click 'Set Up'"
echo ""
echo "4. ⚙️ Configure OAuth:"
echo "   - Go to 'Instagram Graph API' → 'Basic Display'"
echo "   - Add redirect URI: http://localhost:3001/api/instagram/auth/callback"
echo "   - Add Privacy Policy URL: http://localhost:3002/privacy-policy.html"
echo "   - Add Terms of Service URL: http://localhost:3002/terms-of-service.html"
echo "   - Add App Website URL: http://localhost:3002"
echo "   - Go to 'Facebook Login' → 'Settings' (if available)"
echo "   - Add same redirect URI and App Domains: localhost"
echo ""
echo "5. 📱 Upload App Icon:"
echo "   - Go to 'Settings' → 'Basic'"
echo "   - Upload app icon (1024x1024)"
echo "   - Use generated icon: assets/app-icon.svg"
echo "   - Or convert to PNG: open scripts/generate-png-icon.html"
echo ""
echo "6. 📋 Get your credentials:"
echo "   - App ID: Settings → Basic → App ID"
echo "   - App Secret: Settings → Basic → App Secret (click 'Show')"
echo ""
echo "7. 📱 Set up Instagram Business Account:"
echo "   - Open Instagram app"
echo "   - Go to Settings → Account"
echo "   - Switch to 'Business' or 'Creator' account"
echo "   - Complete business account setup"
echo ""
echo "8. 🔑 Update your .env file with these values:"
echo "   INSTAGRAM_CLIENT_ID=your_instagram_app_id"
echo "   INSTAGRAM_CLIENT_SECRET=your_instagram_app_secret"
echo "   INSTAGRAM_REDIRECT_URI=http://localhost:3001/api/instagram/auth/callback"
echo ""
echo "9. 📄 Start legal documents server (in a new terminal):"
echo "   node scripts/serve-legal-docs.js"
echo ""
echo "10. 🧪 Test the setup:"
echo "   npm run dev"
echo "   # Then test: http://localhost:3001/api/instagram/auth/url"
echo ""
echo "📚 For detailed instructions, see:"
echo "   - INSTAGRAM_LOGIN_SETUP_GUIDE.md"
echo "   - INSTAGRAM_OFFICIAL_IMPLEMENTATION.md"
echo ""
echo "🎉 Advantages of Instagram Login:"
echo "   ✅ Simpler setup (no Facebook Page required)"
echo "   ✅ Direct Instagram integration"
echo "   ✅ Fewer dependencies"
echo "   ✅ Cleaner authentication flow"
echo ""
echo "❓ Need help? Check the setup guide for troubleshooting tips!"
